name: Publish package.zip
description: 'Publish package.zip'

inputs:
  tag_name:
    description: 'The name of the release tag to publish against'
    type: string
    required: true
  token:
    description: 'The token to use for uploading the release artifact'
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Upload Release Artifact
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
      run: gh release upload ${{ inputs.tag_name }} package.zip --clobber
