name: Publish Package
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The name of the release tag to publish against'
        type: string
        required: true
      dry_run:
        description: 'Is this a dry run. If so no package will be published.'
        type: boolean
        required: true

jobs:
  build-publish:
    runs-on: ubuntu-latest
    # Needed to get tokens during publishing.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/ci

      - uses: ./.github/actions/publish
        if: ${{ !inputs.dry_run }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ inputs.tag_name }}
