name: Publish Package
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The name of the release tag to publish against'
        type: string
        required: true
      dry_run:
        description: 'Is this a dry run. If so no package will be published.'
        type: boolean
        required: true
      publish_release:
        description: 'Publish (un-draft) the release after all artifacts are uploaded?'
        type: boolean
        required: false
        default: true

jobs:
  build-publish:
    runs-on: ubuntu-latest
    # Needed to get tokens during publishing.
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/ci

      - uses: ./.github/actions/publish
        if: ${{ format('{0}', inputs.dry_run) == 'false' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ inputs.tag_name }}

  publish-release:
    needs: ['build-publish']
    if: ${{ format('{0}', inputs.dry_run) == 'false' && format('{0}', inputs.publish_release) == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ inputs.tag_name }}
        run: >
          gh release edit "$TAG_NAME"
          --repo ${{ github.repository }}
          --draft=false
