name: Run Release Please

on:
  push:
    branches:
      - main

jobs:
  release-package:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed if using OIDC to get release secrets.
      contents: write # Contents and pull-requests are for release-please to make releases.
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        with:
          fetch-depth: 0 # If you only need the current version keep this.

      - uses: ./.github/actions/ci
        if: ${{ steps.release.outputs.releases_created == 'true' }}

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created == 'true' }}
        uses: ./.github/actions/publish
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.release.outputs.tag_name }}
